/*
    id: 
    image:
    userName:
    lastMessage:
    lastMessageTime:
    unreadMessageCount:
    isMuted:
    isGroup:
    groupName:
    userJoined:
    newUserName:
*/

const Data = [
    {
        id: 1,
        image: require('../assets/SGCodes.jpg'),
        userName: 'John',
        lastMessage: '',
        userJoined: true,
        newUserName: "S.G.",
        lastMessageTime: '1:00 PM',
        unreadMessageCount: 0,
        groupName: "S.G.Codes",
        isGroup: true,
    },
    {
        id: 2,
        image: require('../assets/user2.jpg'),
        userName: 'Kirti',
        lastMessage: '',
        newUserName: 'Amit',
        lastMessageTime: 'Mon',
        unreadMessageCount: 10,
        groupName: 'Creators',
        isGroup: true,
    },
    {
        id: 3,
        image: require('../assets/user3.jpg'),
        userName: 'Aashish',
        lastMessage: '',
        userJoined: false,
        isMuted: true,
        lastMessageTime: '7:06 AM',
        unreadMessageCount: 1065,
        isGroup: false,
    },
    {
        id: 4,
        image: require('../assets/user4.jpg'),
        userName: 'Vijay',
        lastMessage: '',
        userJoined: false,
        isMuted: true,
        lastMessageTime: '5:02 PM',
        unreadMessageCount: 0,
        isGroup: false,
    },
    {
        id: 5,
        image: require('../assets/NodeJs.png'),
        userName: 'Martha',
        lastMessage: '',
        userJoined: false,
        newUserName: "Kishan",
        lastMessageTime: '10:00 PM',
        unreadMessageCount: 0,
        groupName: 'Node & React Learners',
        isGroup: true,
    },
    {
        id: 6,
        image: require('../assets/Jobs.png'),
        userName: 'Chris',
        lastMessage: '',
        userJoined: true,
        newUserName: "Anand",
        groupName: "Job Notify",
        lastMessageTime: '4:37 PM',
        unreadMessageCount: 100,
        isGroup: true,
    },
    {
        id: 7,
        image: require('../assets/user7.jpg'),
        userName: 'Simran',
        lastMessage: '',
        userJoined: false,
        lastMessageTime: '9:58 PM',
        unreadMessageCount: 8,
        isGroup: false,
    },
    {
        id: 8,
        image: require('../assets/user8.jpg'),
        userName: 'Jessica',
        lastMessage: '',
        userJoined: false,
        lastMessageTime: '1:05 AM',
        unreadMessageCount: 0,
        isGroup: false,
    },
    {
        id: 9,
        image: require('../assets/Android.png'),
        userName: 'John',
        isMuted: true,
        lastMessage: '',
        userJoined: false,
        lastMessageTime: 'Thur',
        unreadMessageCount: 1,
        groupName: "Android Champions",
        isGroup: true,
    },
    {
        id: 10,
        image: require('../assets/user10.jpg'),
        userName: 'Clarence',
        isMuted: false,
        lastMessage: '',
        userJoined: false,
        lastMessageTime: '6:30 PM',
        unreadMessageCount: 19,
        isGroup: false,
    },
    {
        id: 11,
        image: require('../assets/user11.jpg'),
        userName: 'Edward',
        lastMessage: '',
        userJoined: false,
        lastMessageTime: '10:05 AM',
        unreadMessageCount: 25,
        isGroup: false,
    },
    {
        id: 12,
        image: require('../assets/Friends.jpg'),
        newUserName: 'Jesse',
        lastMessage: '',
        userJoined: true,
        lastMessageTime: 'Now',
        unreadMessageCount: 5,
        isGroup: true,
        groupName: "Friends",
        isMuted: true
    },
    {
        id: 13,
        image: require('../assets/user13.jpg'),
        userName: 'Peter',
        lastMessage: '',
        userJoined: false,
        lastMessageTime: '4:30 PM',
        unreadMessageCount: 0,
        isGroup: false,
    },
    {
        id: 14,
        image: require('../assets/user14.jpg'),
        userName: 'Julius',
        lastMessage: '',
        userJoined: false,
        lastMessageTime: 'Wed',
        unreadMessageCount: 10,
        isGroup: false,
    },
    {
        id: 15,
        image: require('../assets/user15.jpg'),
        userName: 'Roosie',
        lastMessage: '',
        userJoined: false,
        lastMessageTime: '1:00 PM',
        unreadMessageCount: 22,
        isGroup: false,
    },
    {
        id: 16,
        image: require('../assets/user16.jpg'),
        userName: 'Alex',
        lastMessage: '',
        userJoined: false,
        lastMessageTime: 'Mon',
        unreadMessageCount: 0,
        isGroup: false,
    },
    {
        id: 17,
        image: require('../assets/user17.jpg'),
        userName: 'Issac',
        isMuted: true,
        lastMessage: '',
        userJoined: false,
        lastMessageTime: '7:10 PM',
        unreadMessageCount: 5,
        isGroup: false,
    }, 
    {
        id: 18,
        image: require('../assets/user18.jpg'),
        userName: 'Sarthak',
        isMuted: false,
        lastMessage: '',
        userJoined: false,
        lastMessageTime: '7:10 PM',
        unreadMessageCount: 508,
        isGroup: true,
        groupName: "Rockers"
    }, 
    {
        id: 19,
        image: require('../assets/user19.jpg'),
        userName: 'Emma',
        isMuted: false,
        lastMessage: '',
        userJoined: false,
        lastMessageTime: '11:34 PM',
        unreadMessageCount: 12,
        isGroup: false,
    }, 
    {
        id: 20,
        image: require('../assets/user20.jpg'),
        userName: 'Ronald',
        isMuted: true,
        lastMessage: '',
        userJoined: false,
        lastMessageTime: '9:49 AM',
        unreadMessageCount: 36,
        isGroup: false,
    },
    {
        id: 21,
        image: require('../assets/user21.jpg'),
        userName: 'Sophia',
        isMuted: false,
        lastMessage: '',
        userJoined: false,
        lastMessageTime: 'Fri',
        unreadMessageCount: 0,
        isGroup: false,
    },
    {
        id: 22,
        image: require('../assets/SonyMusic.png'),
        isMuted: true,
        lastMessage: '',
        userJoined: true,
        newUserName: "Mia",
        lastMessageTime: 'Now',
        unreadMessageCount: 0,
        isGroup: true,
        groupName: "Sony Music"
    }, 
]

export default Data;
